// MIT License

// Copyright (c) 2022 EASE lab

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bert/bert.proto

package bert

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e3207e7ccc7498, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	MinLatency           int64    `protobuf:"varint,1,opt,name=min_latency,json=minLatency,proto3" json:"min_latency,omitempty"`
	MaxLatency           int64    `protobuf:"varint,2,opt,name=max_latency,json=maxLatency,proto3" json:"max_latency,omitempty"`
	MeanLatency          int64    `protobuf:"varint,3,opt,name=mean_latency,json=meanLatency,proto3" json:"mean_latency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e3207e7ccc7498, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMinLatency() int64 {
	if m != nil {
		return m.MinLatency
	}
	return 0
}

func (m *HelloReply) GetMaxLatency() int64 {
	if m != nil {
		return m.MaxLatency
	}
	return 0
}

func (m *HelloReply) GetMeanLatency() int64 {
	if m != nil {
		return m.MeanLatency
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "bert.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "bert.HelloReply")
}

func init() { proto.RegisterFile("proto/bert/bert.proto", fileDescriptor_93e3207e7ccc7498) }

var fileDescriptor_93e3207e7ccc7498 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xbb, 0x4f, 0xc3, 0x30,
	0x10, 0x06, 0x70, 0x4a, 0x2b, 0x1e, 0xd7, 0x0e, 0xc8, 0x12, 0x12, 0x62, 0x01, 0x3c, 0xb1, 0x34,
	0x91, 0x5a, 0x31, 0xb2, 0xb0, 0xc0, 0xc0, 0x94, 0x6e, 0x2c, 0xc8, 0x89, 0x4e, 0xc4, 0x92, 0x1f,
	0x89, 0xed, 0x98, 0xf8, 0xbf, 0x47, 0xb9, 0x04, 0x42, 0x17, 0xeb, 0xf3, 0xa7, 0x9f, 0xac, 0xf3,
	0xc1, 0x75, 0xe3, 0x6c, 0xb0, 0x79, 0x89, 0x2e, 0xd0, 0x91, 0xd1, 0x9d, 0xad, 0x86, 0xcc, 0x39,
	0x6c, 0xde, 0x50, 0x29, 0x5b, 0x60, 0xdb, 0xa1, 0x0f, 0x8c, 0xc1, 0xca, 0x08, 0x8d, 0x37, 0x8b,
	0xfb, 0xc5, 0xe3, 0x65, 0x41, 0x99, 0xb7, 0x00, 0x93, 0x69, 0x54, 0x62, 0x77, 0xb0, 0xd6, 0xd2,
	0x7c, 0x2a, 0x11, 0xd0, 0x54, 0x89, 0xe0, 0xb2, 0x00, 0x2d, 0xcd, 0xfb, 0xd8, 0x10, 0x10, 0xfd,
	0x1f, 0x38, 0x9d, 0x80, 0xe8, 0x7f, 0xc1, 0x03, 0x6c, 0x34, 0x8a, 0xf9, 0x89, 0x25, 0x89, 0xf5,
	0xd0, 0x4d, 0x64, 0xf7, 0x0c, 0xe7, 0xaf, 0x0e, 0x31, 0xa0, 0x63, 0x3b, 0xb8, 0x38, 0x88, 0x44,
	0x03, 0x30, 0x96, 0xd1, 0x07, 0xfe, 0x4f, 0x7c, 0x7b, 0x75, 0xd4, 0x35, 0x2a, 0xf1, 0x93, 0x97,
	0xa7, 0x8f, 0xfd, 0x97, 0x0c, 0x75, 0x57, 0x66, 0x95, 0xd5, 0x79, 0xac, 0x65, 0xc4, 0xad, 0x47,
	0x17, 0xd1, 0x29, 0xf4, 0x3e, 0x8f, 0x87, 0x6f, 0xe1, 0xf4, 0x76, 0xdc, 0xcb, 0xbc, 0x9d, 0xf2,
	0x8c, 0xf2, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xf8, 0xdd, 0x99, 0x32, 0x01, 0x00, 0x00,
}
