apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-currencyservice
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=7000
            - --function-name=currencyservice
            - --generator=unique
            - --value=100
            - --function-method=Convert
        - image: docker.io/vhiveease/onlineshop-currencyservice:latest
          env:
          - name: PORT
            value: "7000"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"