# MIT License

# Copyright (c) 2022 EASE lab

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: checkoutservice
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=5050
            - --function-name=checkoutservice
            - --generator=unique
            - --value=12345
        # Function ---
        - name: function
          image: docker.io/vhiveease/onlineshop-checkoutservice:latest
          env:
          - name: PORT
            value: "5050"
          - name: SHIPPING_SERVICE_ADDR
            value: "checkoutservice-shipping.default.svc.cluster.local:80"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "checkoutservice-prodcat.default.svc.cluster.local:80"
          - name: CART_SERVICE_ADDR
            value: "checkoutservice-cart.default.svc.cluster.local:80"
          - name: CURRENCY_SERVICE_ADDR
            value: "checkoutservice-currency.default.svc.cluster.local:80"
          - name: EMAIL_SERVICE_ADDR
            value: "checkoutservice-email.default.svc.cluster.local:80"
          - name: PAYMENT_SERVICE_ADDR
            value: "checkoutservice-payment.default.svc.cluster.local:80"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"


---
# Dependant functions
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: checkoutservice-shipping
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/onlineshop-shippingservice:latest
          env:
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          ports:
            - name: h2c
              containerPort: 50051

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: checkoutservice-prodcat
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: vhiveease/onlineshop-productcatalogservice:latest
          env:
          # - name: PORT
          #   value: "3550"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          ports:
            - name: h2c
              containerPort: 3550

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: checkoutservice-cart
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: vhiveease/onlineshop-cartservice:latest
          env:
          # - name: PORT
          #   value: "7070"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          ports:
            - name: h2c
              containerPort: 7070

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: checkoutservice-currency
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: vhiveease/onlineshop-currencyservice:latest
          env:
          # - name: PORT
          #   value: "7000"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          ports:
            - name: h2c
              containerPort: 7000

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: checkoutservice-email
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: vhiveease/onlineshop-emailservice:latest
          env:
          # - name: PORT
          #   value: "8080"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          ports:
            - name: h2c
              containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: checkoutservice-payment
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: vhiveease/onlineshop-paymentservice:latest
          env:
          # - name: PORT
          #   value: "50052"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          ports:
            - name: h2c
              containerPort: 5052

